# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import python_agent_pb2 as python__agent__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in python_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/pixell.python_agent.PythonAgent/Execute',
                request_serializer=python__agent__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=python__agent__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.StreamExecute = channel.unary_stream(
                '/pixell.python_agent.PythonAgent/StreamExecute',
                request_serializer=python__agent__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=python__agent__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.GetSessionState = channel.unary_unary(
                '/pixell.python_agent.PythonAgent/GetSessionState',
                request_serializer=python__agent__pb2.SessionStateRequest.SerializeToString,
                response_deserializer=python__agent__pb2.SessionStateResponse.FromString,
                _registered_method=True)
        self.RetryWithPatch = channel.unary_unary(
                '/pixell.python_agent.PythonAgent/RetryWithPatch',
                request_serializer=python__agent__pb2.RetryRequest.SerializeToString,
                response_deserializer=python__agent__pb2.ExecuteResponse.FromString,
                _registered_method=True)


class PythonAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Primary execution method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExecute(self, request, context):
        """Streaming execution for real-time output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionState(self, request, context):
        """Get session state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryWithPatch(self, request, context):
        """Retry with patch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=python__agent__pb2.ExecuteRequest.FromString,
                    response_serializer=python__agent__pb2.ExecuteResponse.SerializeToString,
            ),
            'StreamExecute': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamExecute,
                    request_deserializer=python__agent__pb2.ExecuteRequest.FromString,
                    response_serializer=python__agent__pb2.StreamChunk.SerializeToString,
            ),
            'GetSessionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionState,
                    request_deserializer=python__agent__pb2.SessionStateRequest.FromString,
                    response_serializer=python__agent__pb2.SessionStateResponse.SerializeToString,
            ),
            'RetryWithPatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryWithPatch,
                    request_deserializer=python__agent__pb2.RetryRequest.FromString,
                    response_serializer=python__agent__pb2.ExecuteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pixell.python_agent.PythonAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pixell.python_agent.PythonAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixell.python_agent.PythonAgent/Execute',
            python__agent__pb2.ExecuteRequest.SerializeToString,
            python__agent__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pixell.python_agent.PythonAgent/StreamExecute',
            python__agent__pb2.ExecuteRequest.SerializeToString,
            python__agent__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixell.python_agent.PythonAgent/GetSessionState',
            python__agent__pb2.SessionStateRequest.SerializeToString,
            python__agent__pb2.SessionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryWithPatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixell.python_agent.PythonAgent/RetryWithPatch',
            python__agent__pb2.RetryRequest.SerializeToString,
            python__agent__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
